### ISSUE TITLE
Rebase from trunk

### ISSUE THREAD

**Issue by bbenninger** [Shirakumo/cl-gamepad#1]
For completeness, the libstem_gamepad fork that this is built on should probably be rebased from master, to at least pick up

https://github.com/ThemsAllTook/libstem_gamepad/commit/de3d4ca0b9a6017b4ee8643287012a9a056521d5

(great work btw!)

**Comment by Shinmera** [comment]
Should be mentioned on https://github.com/Shirakumo/libstem_gamepad instead then

**Comment by bbenninger** [comment]
Agreed, but that project wasn't accepting issues, so that's how this ended up here.

**Comment by Shinmera** [comment]
Oh, I'm sorry then. For some reason github deactivated issues by default on there. Fixed now, thanks.
