### ISSUE TITLE
Type error when quickloading cl-gamepad

### ISSUE THREAD

**Issue by RealSharpness** [Shirakumo/cl-gamepad#18]
Error: `#<Vector @ #x2293c6d2>' is not of the expected type `NUMBER'
[condition type: TYPE-ERROR]

Point of error is the GUID but I don't have the ability to diagnose it.

After that I tried (gamepad:init) to see if it would work anyway, but it gave me the platform not supported error.

**Comment by Shinmera** [comment]
what implementation and platform is this? what's the stack trace?

**Comment by RealSharpness** [comment]
Allegro CL
Windows 11, 64-bit operating system, x64-based processor

This is what I get calling backtrace:

```
CFFI-SYS:NULL-POINTER-P <-
  (METHOD INITIALIZE-INSTANCE :AFTER ...) <- (:INTERNAL (:ANONYMOUS-LAMBDA 169) 0) <- COM:GUID <- [... EXCL::%EVAL ] <- EVAL <- LOAD <-
  (:INTERNAL ASDF/LISP-BUILD:LOAD* 0) <- UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS <-
  ASDF/LISP-BUILD:CALL-WITH-MUFFLED-LOADER-CONDITIONS <- ASDF/LISP-BUILD:LOAD* <- ASDF/LISP-ACTION:PERFORM-LISP-LOAD-FASL <-
  (METHOD ASDF-ACTION:PERFORM (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)) <-
  (:INTERNAL (:EFFECTIVE-METHOD 2 NIL ...) 0) <- (METHOD ASDF-ACTION:PERFORM-WITH-RESTARTS (T T)) <-
  (METHOD ASDF-ACTION:PERFORM-WITH-RESTARTS (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)) <-
  (METHOD ASDF-ACTION:PERFORM-WITH-RESTARTS :AROUND ...) <- (:INTERNAL (:EFFECTIVE-METHOD 2 NIL ...) 0) <-
  (METHOD ASDF/PLAN:PERFORM-PLAN (LIST)) <- (FLET (METHOD ASDF/PLAN:PERFORM-PLAN :AROUND ...) EXCL::CONTINUATION) <-
  (METHOD ASDF/PLAN:PERFORM-PLAN :AROUND ...) <- (:INTERNAL (:EFFECTIVE-METHOD 1 T ...) 0) <- (METHOD ASDF/PLAN:PERFORM-PLAN (T)) <-
  (FLET (METHOD ASDF/PLAN:PERFORM-PLAN :AROUND ...) EXCL::CONTINUATION) <- (METHOD ASDF/PLAN:PERFORM-PLAN :AROUND ...) <-
  (:INTERNAL (:EFFECTIVE-METHOD 1 T ...) 0) <- (METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) <-
  (:INTERNAL (:EFFECTIVE-METHOD 2 T ...) 0) <- (:INTERNAL (METHOD ASDF/OPERATE:OPERATE :AROUND ...) 0) <-
  ASDF/CACHE:CALL-WITH-ASDF-CACHE <- (METHOD ASDF/OPERATE:OPERATE :AROUND ...)(:INTERNAL (:EFFECTIVE-METHOD 2 T ...) 0) <-
```

**Comment by Shinmera** [comment]
I don't have access to Allegro so I can't debug this issue. From the trace I'm not even sure if the problem is in this library or in com-on.

**Comment by RealSharpness** [comment]
Seems to be an Allegro-specific issue. I'll let you know if I make any progress.

**Comment by 3b** [comment]
might try moving the `CFFI:FOREIGN-POINTER` clause in the `typecase` at https://github.com/Shinmera/com-on/blob/master/guid.lisp#L149-L153 after the `NULL` clause and see if that helps?

Not sure if allegro just thinks pretty much anything is a `foreign-pointer` (which that change would handle), or if cffi shouldn't be assuming `foreign-pointer`s are integers.
