### ISSUE TITLE
Compile error on windows

### ISSUE THREAD

**Issue by azimut** [Shirakumo/cl-gamepad#5]
There seems to be Windows only problem with

https://github.com/Shirakumo/cl-gamepad/blob/7517a09d5c5298fc6d29625412fe9079ff54d62d/mapping.lisp#L101

Is not compiling on travis at least https://travis-ci.com/github/azimut/trial-travis/builds/159818367#L167

fwiw, I don't know why this would be Windows only problem but saw it before in https://github.com/lispgames/cl-sdl2/issues/122#issuecomment-552800523

**Comment by Shinmera** [comment]
Fix git to not fuck up your line encodings when cloning.
